server:
  port: 8082

spring:
  application:
    name: consumer-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    # 配置负载均衡策略
    loadbalancer-clients:
      provider-service:
        # 可切换为以下三种策略：
        # - org.springframework.cloud.loadbalancer.core.RoundRobinLoadBalancer  # 轮询策略（默认）
        # - org.springframework.cloud.loadbalancer.core.RandomLoadBalancer  # 随机策略
        # - com.example.consumer.config.CustomLoadBalancer  # 自定义策略
        type: com.example.consumer.config.CustomLoadBalancer

# Feign配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  compression:
    request:
      enabled: true
    response:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 