server:
  port: 8081

spring:
  application:
    name: service-provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

message:
  greeting: "你好，这是服务提供者的更新消息"
